# Generated by Django 3.1.7 on 2021-03-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30, unique=True, verbose_name='section')),
                ('order', models.IntegerField(verbose_name='order')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'db_table': 'section_table',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('html', models.TextField(verbose_name='html')),
                ('order', models.IntegerField(verbose_name='order')),
                ('hash_tag', models.TextField(verbose_name='hash_tag')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.section')),
            ],
        ),
    ]
